/* eslint-disable no-shadow */
// eslint-disable-next-line import/prefer-default-export
enum HttpStatusCode {

    CONTINUE = 100,

    /**
     * The requester has asked the server to switch protocols and the server has agreed to do so.
     */
    SWITCHING_PROTOCOLS = 101,

    PROCESSING = 102,

    EARLY_HINTS = 103,

    OK = 200,

    /**
     * The request has been fulfilled, resulting in the creation of a new resource.
     */
    CREATED = 201,

    ACCEPTED = 202,

    NON_AUTHORITATIVE_INFORMATION = 203,

    NO_CONTENT = 204,

    PARTIAL_CONTENT = 206,

    MULTI_STATUS = 207,

    MULTIPLE_CHOICES = 300,

    MOVED_PERMANENTLY = 301,

    FOUND = 302,

    SEE_OTHER = 303,

    NOT_MODIFIED = 304,

    USE_PROXY = 305,

    TEMPORARY_REDIRECT = 307,

    PERMANENT_REDIRECT = 308,

    BAD_REQUEST = 400,

    UNAUTHORIZED = 401,

    PAYMENT_REQUIRED = 402,

    FORBIDDEN = 403,

    NOT_FOUND = 404,

    METHOD_NOT_ALLOWED = 405,

    NOT_ACCEPTABLE = 406,

    PROXY_AUTHENTICATION_REQUIRED = 407,

    REQUEST_TIMEOUT = 408,

    CONFLICT = 409,

    GONE = 410,

    LENGTH_REQUIRED = 411,

    PRECONDITION_FAILED = 412,

    PAYLOAD_TOO_LARGE = 413,

    URI_TOO_LONG = 414,

    UNSUPPORTED_MEDIA_TYPE = 415,

    RANGE_NOT_SATISFIABLE = 416,

    EXPECTATION_FAILED = 417,

    I_AM_A_TEAPOT = 418,

    ENHANCE_YOUR_CALM = 420,

    MISDIRECTED_REQUEST = 421,

    UNPROCESSABLE_ENTITY = 422,

    LOCKED = 423,

    FAILED_DEPENDENCY = 424,

    TOO_EARLY = 425,

    UPGRADE_REQUIRED = 426,

    TOO_MANY_REQUESTS = 429,

    REQUEST_HEADER_FIELDS_TOO_LARGE = 431,

    NO_RESPONSE = 444,

    BLOCKED_BY_WINDOWS_PARENTAL_CONTROL = 450,

    UNAVAILABLE_FOR_LEGAL_REASONS = 451,

    HTTP_REQUEST_SENT_TO_HTTPS_PORT = 497,

    TOKEN_EXPIRED_OR_INVALIDI = 498,

    CLIENT_CLOSED_REQUEST = 499,

    INTERNAL_SERVER_ERROR = 500,

    NOT_IMPLEMENTED = 501,

    BAD_GATEWAY = 502,

    SERVICE_UNAVAILABLE = 503,

    GATEWAY_TIMEOUT = 504,

    HTTP_VERSION_NOT_SUPPORTED = 505,

    VARIANT_ALSO_NEGOTIATES = 506,

    INSUFFICIENT_STORAGE = 507,

    LOOP_DETECTED = 508,

    BANDWITH_LIMIT_EXCEEDED = 509,

    NOT_EXTENDED = 510,

    NETWORK_AUTHENTICATION_REQUIRED = 511,

    WEB_SERVER_IS_DOWN = 521,

    CONNECTION_TIMED_OUT = 522,

    ORIGIN_IS_UNREACHABLE = 523,

    SSL_HANDSHAKE_FAILED = 525,

    NETWORK_CONNECT_TIMEOUT_ERROR = 599
}

export default HttpStatusCode;
